repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=650']
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: no-commit-to-branch
    args: ['--branch', 'main']

- repo: local
  hooks:
    - id: encryption-check
      name: Ansible Vault Encryption Check
      description: Checks that vault files are encrypted
      entry: /usr/local/bin/encryption-check.sh
      files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
      language: script
